### PR TITLE
Add continuous integration

### PR DESCRIPTION
**Pull request by Tyler887**
@NikitaIvanovV, in order to play the game, you need to have GitHub Actions. An artifact can be used to make it downloadable. Simple, right?

### CODE REVIEW

**Comment by NikitaIvanovV** [comment]
Why would anyone need GitHub actions to play the game?

**Comment by Tyler887** [comment]
> Why would anyone need GitHub actions to play the game?

I am unable to find an apk or exe to play it, so I am working on this thing. It shall let you publish the game, by creating a release (see the sidebar of the "Code" tab).

GitHub Actions is official: https://github.com/features/actions

Note: When complete, this action may contain [actions](https://github.com/marketplace/actions) that are not certified by GitHub.

**Comment by Tyler887** [comment]
Sorry, you may have to do this yourself. My CI keeps failing.

**Comment by NikitaIvanovV** [comment]
You need to compile the game to play it, you don't need GitHub actions to do that. Also, since you mentioned exe, apk files: there is no Windows or Android platform support yet, only Linux.

**Comment by NikitaIvanovV** [comment]
Btw, the file you added in this PR doesn't seem correct: the libs you added are not needed (you only need SDL2) and the build commands look wrong as well.

**Pull request closed without merging**
